#!/bin/bash
#
# At this time this script is source'd by:
#    PCAPs-stream-clean.sh
#    PCAPs-work-prep-sep.sh
#    tcpdu-PDUs.sh
#    tshark-hosts-conv.sh
#    tshark-http-uri.sh
#    tshark-streams.sh
#    uncenz-2nd
# to use the wireshark and its associates built from git sources when the
# regular install is missing

TEST_WIRESHARK=$(which wireshark)
#echo \$TEST_WIRESHARK: $TEST_WIRESHARK
if [ "X${TEST_WIRESHARK}" == "X" ]; then
    if [ ! -d "$RUN_BUILD_DIR" ]; then
        echo "There is no regular Wireshark install, but"
        echo "  neither you gave \$RUN_BUILD_DIR in /home/$USER/.bashrc"
        echo "  or \$RUN_BUILD_DIR is not a dir."
        ls -l $RUN_BUILD_DIR
        echo "(ls -l $RUN_BUILD_DIR)"
        echo "Did you forget to source /home/$USER/.bashrc ?"
        exit
    else
        echo \$RUN_BUILD_DIR: $RUN_BUILD_DIR
    fi
    echo "(\$RUN_BUILD_DIR)"
    #read NOOP
    WIRESHARK_RUN_FROM_BUILD_DIRECTORY=1
    WIRESHARK=$RUN_BUILD_DIR/wireshark
    TSHARK=$RUN_BUILD_DIR/tshark
    EDITCAP=$RUN_BUILD_DIR/editcap
    MERGECAP=$RUN_BUILD_DIR/mergecap
    CAPINFOS=$RUN_BUILD_DIR/capinfos
else
    WIRESHARK=$(which wireshark)
    TSHARK=$(which tshark)
    EDITCAP=$(which editcap)
    MERGECAP=$(which mergecap)
    CAPINFOS=$(which capinfos)
fi
